In [281]:
import pandas as pd
import numpy as np
from numpy.lib.stride_tricks import as_strided


from pandas._libs import algos as libalgos
from datetime import datetime

#### understand strides, https://stackoverflow.com/questions/53097952/how-to-understand-numpy-strides-for-layman

In [24]:
df[0].values.strides[0]

16

In [27]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
a.strides

(12, 4)

#### check rolling_spearman_quick

In [116]:
np.random.seed(10)
df = pd.DataFrame(np.random.randn(100, 3),columns=['a','b','c'])
df = df.astype(float)


In [117]:
df

a         b         c
0   1.331587  0.715279 -1.545400
1  -0.008384  0.621336 -0.720086
2   0.265512  0.108549  0.004291
3  -0.174600  0.433026  1.203037
4  -0.965066  1.028274  0.228630
..       ...       ...       ...
95  0.308668  0.892564  0.011023
96  0.980074 -2.395572 -0.857523
97 -0.364278  0.503927  0.188331
98  1.085227  0.356939  0.207330
99 -0.145065  0.163904  0.829512

[100 rows x 3 columns]

In [55]:
seqa = df[0].values
seqb = df[1].values
stridea = seqa.strides[0]

In [62]:
window = 5

In [63]:
ssa = as_strided(seqa, shape=[len(seqa) - window + 1, window], strides=[stridea, stridea])

In [71]:

stridea = seqa.strides[0]
ssa = as_strided(seqa, shape=[len(seqa) - window + 1, window], strides=[stridea, stridea])
strideb = seqa.strides[0]
ssb = as_strided(seqb, shape=[len(seqb) - window + 1, window], strides =[strideb, strideb])
ar = pd.DataFrame(ssa)
br = pd.DataFrame(ssb)
ar = ar.rank(1)
br = br.rank(1)

In [74]:
corrs = ar.corrwith(br, 1)

In [106]:
def rolling_spearman_corr(df, window, cols = []):
    idx = df.index
    if len(cols)==2:
        ssa = df[cols[0]].values
        ssb = df[cols[1]].values
        ret = rolling_spearman_quick(ssa, ssb, window)
    elif len(cols)==0:
        return 'TBA'
    else:
        raise ValueError("cols must of list of two or zero elements")
        
    return pd.DataFrame(ret, index=idx, columns=)

In [121]:
numeric_df = df._get_numeric_data()
cols = numeric_df.columns
idx = cols.copy()
mat = numeric_df.to_numpy(dtype=float, na_value=np.nan, copy=False)

In [129]:
min_periods =5
correl = libalgos.nancorr_spearman(mat, minp=min_periods)

In [137]:
def rolling_rank_corr(df, window):
    pass

In [ ]:
stridea = seqa.strides[0]
ssa = as_strided(seqa, shape=[len(seqa) - window + 1, window], strides=[stridea, stridea])
strideb = seqa.strides[0]
ssb = as_strided(seqb, shape=[len(seqb) - window + 1, window], strides =[strideb, strideb])
ar = pd.DataFrame(ssa)
br = pd.DataFrame(ssb)
ar = ar.rank(1)
br = br.rank(1)

In [ ]:
window = 5
n = 20
p = 3
x = np.asarray(range(1,n*p+1), np.float64).reshape(n,p)
x = np.random.randn(n, p)
display(x)
x.strides

mat_3d = as_strided(x, shape=(n-window+1, window, p), strides=(x.strides[0], x.strides[0], x.strides[1]))


res = np.array([libalgos.nancorr_spearman(x) for x in mat_3d])

a = np.empty((window-1, p, p,))
a[:] = np.nan

res2 = np.concatenate((a, res))

t = [[i]*p for i in df.index]
flat_list1 = [item for sublist in t for item in sublist]
t2 = [df.columns]*n
flat_list2 = [item for sublist in t2 for item in sublist]
arrays = [flat_list1, flat_list2]
midx = pd.MultiIndex.from_arrays(arrays)

pd.DataFrame(res2.reshape(n*p, p), index=midx, columns=df.columns)

In [261]:
res2.shape

In [270]:
res2

array([[[ nan,  nan,  nan],
        [ nan,  nan,  nan],
        [ nan,  nan,  nan]],

       [[ nan,  nan,  nan],
        [ nan,  nan,  nan],
        [ nan,  nan,  nan]],

       [[ nan,  nan,  nan],
        [ nan,  nan,  nan],
        [ nan,  nan,  nan]],

       [[ nan,  nan,  nan],
        [ nan,  nan,  nan],
        [ nan,  nan,  nan]],

       [[ 1. , -0.7,  0.9],
        [-0.7,  1. , -0.9],
        [ 0.9, -0.9,  1. ]],

       [[ 1. , -0.6,  0.9],
        [-0.6,  1. , -0.7],
        [ 0.9, -0.7,  1. ]],

       [[ 1. , -0.6,  0.4],
        [-0.6,  1. , -0.8],
        [ 0.4, -0.8,  1. ]],

       [[ 1. , -0.5,  0.2],
        [-0.5,  1. , -0.9],
        [ 0.2, -0.9,  1. ]],

       [[ 1. , -0.5,  0.2],
        [-0.5,  1. , -0.9],
        [ 0.2, -0.9,  1. ]],

       [[ 1. , -0.3,  0.5],
        [-0.3,  1. , -0.9],
        [ 0.5, -0.9,  1. ]],

       [[ 1. , -0.1,  0.5],
        [-0.1,  1. , -0.8],
        [ 0.5, -0.8,  1. ]],

       [[ 1. ,  0. ,  0.7],
        [ 0. ,  1. , -0.3]

In [282]:
df.columns = ['a','b','c']
df.index = pd.date_range(datetime(2021,1,1), datetime(2021,1,20))

In [ ]:
df.rolling

In [264]:
img = np.array([[[155,  33, 129],
        [161, 218,   6]],

       [[215, 142, 235],
        [143, 249, 164]],

       [[221,  71, 229],
        [ 56,  91, 120]],

       [[236,   4, 177],
        [171, 105,  40]]])

In [267]:
img.shape

(4, 2, 3)

In [269]:
img.transpose(2,0,1).shape#.reshape(3,-1)


(3, 4, 2)

In [262]:
array([[155, 161, 215, 143, 221,  56, 236, 171],
       [ 33, 218, 142, 249,  71,  91,   4, 105],
       [129,   6, 235, 164, 229, 120, 177,  40]])

SyntaxError: invalid syntax (Temp/ipykernel_23124/2656161451.py, line 1)

In [203]:
a = np.empty((3,3,))
a[:] = np.nan

In [335]:
def rolling_spearman_quick(seqa, seqb, window):
    seqa =seqa.values
    seqb =seqb.values
    stridea = seqa.strides[0]
    ssa = as_strided(seqa, shape=[len(seqa) - window + 1, window], strides=[stridea, stridea])
    strideb = seqa.strides[0]
    ssb = as_strided(seqb, shape=[len(seqb) - window + 1, window], strides =[strideb, strideb])
    ar = pd.DataFrame(ssa)
    br = pd.DataFrame(ssb)
    ar = ar.rank(1)
    br = br.rank(1)
    corrs = ar.corrwith(br, 1)
    return pad(corrs, (window - 1, 0), 'constant', constant_values=np.nan)


def rolling_rank_corr(df, window, y = None, min_periods=1):
    if y is None:
        n, p = df.shape
        x = df.values

        # create rolling 3d array
        mat_3d = as_strided(x, shape=(n-window+1, window, p), strides=(x.strides[0], x.strides[0], x.strides[1]))

        # apply spearman corr
        res = np.array([libalgos.nancorr_spearman(x) for x in mat_3d])

        # produce missing array
        a = np.empty((window-1, p, p,))
        a[:] = np.nan

        # concat
        res2 = np.concatenate((a, res))

        # create index
        t = [[i]*p for i in df.index]
        flat_list1 = [item for sublist in t for item in sublist]
        t2 = [df.columns]*n
        flat_list2 = [item for sublist in t2 for item in sublist]
        arrays = [flat_list1, flat_list2]
        midx = pd.MultiIndex.from_arrays(arrays)

        return pd.DataFrame(res2.reshape(n*p, p), index=midx, columns=df.columns)
    else:
        ret_dict = {}
        for col in df.columns:
            ret_dict[col] = rolling_spearman_quick(df[col], y, window=window)
        return pd.DataFrame(ret_dict, index=df.index)
    

def rollingcorr(df, window, col=None, min_periods=None, method='spearman'):
    if method =='pearson':
        return df.rolling(window).corr(col)
    elif method=='spearman':
        return rolling_rank_corr(df, window, y = col, min_periods=1)
    else:
        raise ValueError(f"method {method} not implemented")

pd.core.frame.DataFrame.rollingcorr=rollingcorr

In [293]:
df = pd.DataFrame(np.random.randn(20, 3))
df.columns = ['a','b','c']
df.index = pd.date_range(datetime(2021,1,1), datetime(2021,1,20))

In [294]:
df.rollingcorr?

Signature: df.rollingcorr(window, min_periods=None, method='spearman')
Docstring: <no docstring>
File:      c:\users\wang\appdata\local\temp\ipykernel_23124\2307588903.py
Type:      method


In [295]:
df[feature_cols].rollingcorr(df[y])

In [295]:
n*p x p

In [325]:
df.rolling(5).corr(None)

a         b         c
2021-01-01 a       NaN       NaN       NaN
           b       NaN       NaN       NaN
           c       NaN       NaN       NaN
2021-01-02 a       NaN       NaN       NaN
           b       NaN       NaN       NaN
           c       NaN       NaN       NaN
2021-01-03 a       NaN       NaN       NaN
           b       NaN       NaN       NaN
           c       NaN       NaN       NaN
2021-01-04 a       NaN       NaN       NaN
           b       NaN       NaN       NaN
           c       NaN       NaN       NaN
2021-01-05 a  1.000000  0.546443 -0.657402
           b  0.546443  1.000000 -0.575079
           c -0.657402 -0.575079  1.000000
2021-01-06 a  1.000000  0.594286 -0.575891
           b  0.594286  1.000000 -0.898535
           c -0.575891 -0.898535  1.000000
2021-01-07 a  1.000000  0.120288 -0.361840
           b  0.120288  1.000000 -0.901667
           c -0.361840 -0.901667  1.000000
2021-01-08 a  1.000000  0.102020 -0.315596
           b  0.102020  1.000000 -0.955359
           c -0.315596 -0.955359  1.000000
2021-01-09 a  1.000000 -0.495537  0.353865
           b -0.495537  1.000000 -0.871025
           c  0.353865 -0.871025  1.000000
2021-01-10 a  1.000000 -0.716667  0.269328
           b -0.716667  1.000000 -0.015558
           c  0.269328 -0.015558  1.000000
2021-01-11 a  1.000000 -0.715964  0.383210
           b -0.715964  1.000000 -0.152404
           c  0.383210 -0.152404  1.000000
2021-01-12 a  1.000000 -0.715156 -0.734309
           b -0.715156  1.000000  0.640940
           c -0.734309  0.640940  1.000000
2021-01-13 a  1.000000  0.839687  0.311398
           b  0.839687  1.000000  0.583876
           c  0.311398  0.583876  1.000000
2021-01-14 a  1.000000  0.867079  0.438056
           b  0.867079  1.000000  0.047665
           c  0.438056  0.047665  1.000000
2021-01-15 a  1.000000  0.867921  0.132972
           b  0.867921  1.000000 -0.177036
           c  0.132972 -0.177036  1.000000
2021-01-16 a  1.000000  0.947233  0.140920
           b  0.947233  1.000000  0.074781
           c  0.140920  0.074781  1.000000
2021-01-17 a  1.000000  0.955696 -0.306041
           b  0.955696  1.000000 -0.145395
           c -0.306041 -0.145395  1.000000
2021-01-18 a  1.000000  0.665849 -0.385622
           b  0.665849  1.000000 -0.711314
           c -0.385622 -0.711314  1.000000
2021-01-19 a  1.000000  0.644194 -0.460348
           b  0.644194  1.000000 -0.616134
           c -0.460348 -0.616134  1.000000
2021-01-20 a  1.000000  0.549817 -0.342525
           b  0.549817  1.000000 -0.687605
           c -0.342525 -0.687605  1.000000

In [299]:
ret1 = df.rolling(5).corr() # nx3 by 3 

In [ ]:
ret1.reset_index().query()

In [303]:
ret1 = df.rolling(5).corr()

In [308]:
df.rolling(5).corr(df['c'])

a         b    c
2021-01-01       NaN       NaN  NaN
2021-01-02       NaN       NaN  NaN
2021-01-03       NaN       NaN  NaN
2021-01-04       NaN       NaN  NaN
2021-01-05 -0.657402 -0.575079  1.0
2021-01-06 -0.575891 -0.898535  1.0
2021-01-07 -0.361840 -0.901667  1.0
2021-01-08 -0.315596 -0.955359  1.0
2021-01-09  0.353865 -0.871025  1.0
2021-01-10  0.269328 -0.015558  1.0
2021-01-11  0.383210 -0.152404  1.0
2021-01-12 -0.734309  0.640940  1.0
2021-01-13  0.311398  0.583876  1.0
2021-01-14  0.438056  0.047665  1.0
2021-01-15  0.132972 -0.177036  1.0
2021-01-16  0.140920  0.074781  1.0
2021-01-17 -0.306041 -0.145395  1.0
2021-01-18 -0.385622 -0.711314  1.0
2021-01-19 -0.460348 -0.616134  1.0
2021-01-20 -0.342525 -0.687605  1.0

In [312]:
ret_dict = {}
for col in df.columns:
    ret_dict[col] = rolling_spearman_quick(df[col], df['c'], window=5)

In [318]:
df.rollingcorr?

Signature: df.rollingcorr(window, col=None, min_periods=None, method='spearman')
Docstring: <no docstring>
File:      c:\users\wang\appdata\local\temp\ipykernel_23124\2319779601.py
Type:      method


In [333]:
df.rollingcorr(5, col=df['c'])

a    b    c
2021-01-01  NaN  NaN  NaN
2021-01-02  NaN  NaN  NaN
2021-01-03  NaN  NaN  NaN
2021-01-04  NaN  NaN  NaN
2021-01-05 -0.3 -0.3  1.0
2021-01-06 -0.3 -0.9  1.0
2021-01-07 -0.3 -0.9  1.0
2021-01-08 -0.2 -0.9  1.0
2021-01-09  0.5 -0.8  1.0
2021-01-10  0.1 -0.1  1.0
2021-01-11  0.0 -0.3  1.0
2021-01-12 -0.7  0.7  1.0
2021-01-13  0.3  0.7  1.0
2021-01-14  0.8  0.3  1.0
2021-01-15  0.6  0.2  1.0
2021-01-16  0.5  0.6  1.0
2021-01-17  0.1  0.2  1.0
2021-01-18 -0.2 -0.3  1.0
2021-01-19 -0.2 -0.5  1.0
2021-01-20 -0.2 -0.2  1.0